title: Alyona Vertsimakha Portfolio
description: A description of my site
baseurl: "" # the subpath of your site, e.g. /blog


remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

# Build settings
markdown: kramdown
